### ISSUE TITLE
Why isn't auth pulling any more?

### ISSUE THREAD

**Issue by justinhandley** [prescottprue/redux-firebasev3#9]
This used to work for me

```
uid: pathToJS(firebase, 'auth/uid'),
```

and is now returning undefined.

Is there a part of the code that hasn't been updated?

**Comment by prescottprue** [comment]
@justinhandley The v0.1.1 release changed quite a bit of code and included a [pull request](https://github.com/prescottprue/redux-firebasev3/pull/6) that also caused some queries to break.

For now I suggest sticking to v0.1.0. Trying to get the new version out as soon as possible to fix these issues. Do you have a repo that you are willing to share in which I can reproduce your error specifically?

v0.1.2 should also include a more full fledged example (instead of just being sample code snippets)

**Comment by prescottprue** [comment]
Examples for v0.1.2 have been made, but still need to roll back this part of the auth.

**Comment by prescottprue** [comment]
@justinhandley Just released `v0.1.2` with the examples as I mentioned.

The authentication functionality is rolled back to how it was in `v0.1.0`, so hopefully it is working again for you. Could you give it a try and let me know?
